# Docker compose file used for local development

services:
  # Microsoft SQL database used for testing
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
    ports:
      - 1433:1433

    environment:
      - MSSQL_SA_PASSWORD=My@Test@Password1
    command: ["/opt/mssql/bin/sqlservr", "--accept-eula", "--reset-sa-password"]

  db2:
    image: icr.io/db2_community/db2:11.5.8.0
    ports:
      - "50000:50000"
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=password
      - DBNAME=dbtest
      - DB2INSTANCE=db2inst1
